indie_app/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from indie_app.views import HomepageView

from django.contrib import admin

urlpatterns = patterns("",
    url(r"^$", HomepageView.as_view(), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/social/", include("social.apps.django_app.urls", namespace="social")),
    url(r"^account/", include("subscription.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^brand/", include('_backend_api.urls')), 
    url(r"^ajax_login/$", TemplateView.as_view(template_name="_global_partials/ajax_login_brand_follow.html")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scrap/urls.py
from __future__ import unicode_literals
from django.conf.urls import patterns, include, url

from scrap._trademark_views import _trademark


urlpatterns = patterns('', 
    url(r'^_internal/trademark_api/', _trademark),
)

indie_app/app/models.py
# Define a custom User class to work with django-social-auth
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

account/forms.py
from __future__ import unicode_literals

import re

try:
    from collections import OrderedDict
except ImportError:
    OrderedDict = None

from django import forms
from django.utils.translation import ugettext_lazy as _

from django.contrib import auth

from account.compat import get_user_model, get_user_lookup_kwargs
from account.conf import settings
from account.hooks import hookset
from account.models import EmailAddress


alnum_re = re.compile(r"^\w+$")


class SignupForm(forms.Form):

    username = forms.CharField(
        label=_("Username"),
        max_length=30,
        widget=forms.TextInput(),
        required=True
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(render_value=False)
    )
    password_confirm = forms.CharField(
        label=_("Password (again)"),
        widget=forms.PasswordInput(render_value=False)
    )
    email = forms.EmailField(
        label=_("Email"),
        widget=forms.TextInput(), required=True)

    code = forms.CharField(
        max_length=64,
        required=False,
        widget=forms.HiddenInput()
    )

    def clean_username(self):
        if not alnum_re.search(self.cleaned_data["username"]):
            raise forms.ValidationError(_("Usernames can only contain letters, numbers and underscores."))
        User = get_user_model()
        lookup_kwargs = get_user_lookup_kwargs({
            "{username}__iexact": self.cleaned_data["username"]
        })
        qs = User.objects.filter(**lookup_kwargs)
        if not qs.exists():
            return self.cleaned_data["username"]
        raise forms.ValidationError(_("This username is already taken. Please choose another."))

    def clean_email(self):
        value = self.cleaned_data["email"]
        qs = EmailAddress.objects.filter(email__iexact=value)
        if not qs.exists() or not settings.ACCOUNT_EMAIL_UNIQUE:
            return value
        raise forms.ValidationError(_("A user is registered with this email address."))

    def clean(self):
        if "password" in self.cleaned_data and "password_confirm" in self.cleaned_data:
            if self.cleaned_data["password"] != self.cleaned_data["password_confirm"]:
                raise forms.ValidationError(_("You must type the same password each time."))
        return self.cleaned_data


class LoginForm(forms.Form):

    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(render_value=False)
    )
    remember = forms.BooleanField(
        label=_("Remember Me"),
        required=False
    )
    user = None

    def clean(self):
        if self._errors:
            return
        user = auth.authenticate(**self.user_credentials())
        if user:
            if user.is_active:
                self.user = user
            else:
                raise forms.ValidationError(_("This account is inactive."))
        else:
            raise forms.ValidationError(self.authentication_fail_message)
        return self.cleaned_data

    def user_credentials(self):
        return hookset.get_user_credentials(self, self.identifier_field)


class LoginUsernameForm(LoginForm):

    username = forms.CharField(label=_("Username"), max_length=30)
    authentication_fail_message = _("The username and/or password you specified are not correct.")
    identifier_field = "username"

    def __init__(self, *args, **kwargs):
        super(LoginUsernameForm, self).__init__(*args, **kwargs)
        field_order = ["username", "password", "remember"]
        if not OrderedDict or hasattr(self.fields, "keyOrder"):
            self.fields.keyOrder = field_order
        else:
            self.fields = OrderedDict((k, self.fields[k]) for k in field_order)


class LoginEmailForm(LoginForm):

    email = forms.EmailField(label=_("Email"))
    authentication_fail_message = _("The email address and/or password you specified are not correct.")
    identifier_field = "email"

    def __init__(self, *args, **kwargs):
        super(LoginEmailForm, self).__init__(*args, **kwargs)
        field_order = ["email", "password", "remember"]
        if not OrderedDict or hasattr(self.fields, "keyOrder"):
            self.fields.keyOrder = field_order
        else:
            self.fields = OrderedDict((k, self.fields[k]) for k in field_order)


class ChangePasswordForm(forms.Form):

    password_current = forms.CharField(
        label=_("Current Password"),
        widget=forms.PasswordInput(render_value=False)
    )
    password_new = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput(render_value=False)
    )
    password_new_confirm = forms.CharField(
        label=_("New Password (again)"),
        widget=forms.PasswordInput(render_value=False)
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_password_current(self):
        if not self.user.check_password(self.cleaned_data.get("password_current")):
            raise forms.ValidationError(_("Please type your current password."))
        return self.cleaned_data["password_current"]

    def clean_password_new_confirm(self):
        if "password_new" in self.cleaned_data and "password_new_confirm" in self.cleaned_data:
            if self.cleaned_data["password_new"] != self.cleaned_data["password_new_confirm"]:
                raise forms.ValidationError(_("You must type the same password each time."))
        return self.cleaned_data["password_new_confirm"]


class PasswordResetForm(forms.Form):

    email = forms.EmailField(label=_("Email"), required=True)

    def clean_email(self):
        value = self.cleaned_data["email"]
        if not EmailAddress.objects.filter(email__iexact=value).exists():
            raise forms.ValidationError(_("Email address can not be found."))
        return value


class PasswordResetTokenForm(forms.Form):

    password = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput(render_value=False)
    )
    password_confirm = forms.CharField(
        label=_("New Password (again)"),
        widget=forms.PasswordInput(render_value=False)
    )

    def clean_password_confirm(self):
        if "password" in self.cleaned_data and "password_confirm" in self.cleaned_data:
            if self.cleaned_data["password"] != self.cleaned_data["password_confirm"]:
                raise forms.ValidationError(_("You must type the same password each time."))
        return self.cleaned_data["password_confirm"]


class SettingsForm(forms.Form):

    email = forms.EmailField(label=_("Email"), required=True)
    timezone = forms.ChoiceField(
        label=_("Timezone"),
        choices=[("", "---------")] + settings.ACCOUNT_TIMEZONES,
        required=False
    )
    if settings.USE_I18N:
        language = forms.ChoiceField(
            label=_("Language"),
            choices=settings.ACCOUNT_LANGUAGES,
            required=False
        )

    def clean_email(self):
        value = self.cleaned_data["email"]
        if self.initial.get("email") == value:
            return value
        qs = EmailAddress.objects.filter(email__iexact=value)
        if not qs.exists() or not settings.ACCOUNT_EMAIL_UNIQUE:
            return value
        raise forms.ValidationError(_("A user is registered with this email address."))

indie_app/app/views.py
import json

from django.conf import settings
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, login

from social.backends.oauth import BaseOAuth1, BaseOAuth2
from social.backends.google import GooglePlusAuth
from social.backends.utils import load_backends
from social.apps.django_app.utils import psa

from example.app.decorators import render_to


def logout(request):
    """Logs out user"""
    auth_logout(request)
    return redirect('/')


def context(**extra):
    return dict({
        'plus_id': getattr(settings, 'SOCIAL_AUTH_GOOGLE_PLUS_KEY', None),
        'plus_scope': ' '.join(GooglePlusAuth.DEFAULT_SCOPE),
        'available_backends': load_backends(settings.AUTHENTICATION_BACKENDS)
    }, **extra)


@render_to('home.html')
def home(request):
    """Home view, displays login mechanism"""
    if request.user.is_authenticated():
        return redirect('done')
    return context()


@login_required
@render_to('home.html')
def done(request):
    """Login complete view, displays user data"""
    return context()


@render_to('home.html')
def validation_sent(request):
    return context(
        validation_sent=True,
        email=request.session.get('email_validation_address')
    )


@render_to('home.html')
def require_email(request):
    backend = request.session['partial_pipeline']['backend']
    return context(email_required=True, backend=backend)


@psa('social:complete')
def ajax_auth(request, backend):
    if isinstance(request.backend, BaseOAuth1):
        token = {
            'oauth_token': request.REQUEST.get('access_token'),
            'oauth_token_secret': request.REQUEST.get('access_token_secret'),
        }
    elif isinstance(request.backend, BaseOAuth2):
        token = request.REQUEST.get('access_token')
    else:
        raise HttpResponseBadRequest('Wrong backend type')
    user = request.backend.do_auth(token, ajax=True)
    login(request, user)
    data = {'id': user.id, 'username': user.username}
    return HttpResponse(json.dumps(data), mimetype='application/json')

indie_app/views.py
from __future__ import unicode_literals 

from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView
from _backend_api.models import Brand

class HomepageView(ListView):

	template_name = 'homepage.html'
	
	model = Brand

	def get_context_data(self, **kwargs):
		context = super(HomepageView, self).get_context_data(**kwargs)
		context['brand_list'] = Brand.objects.filter(brand_state=True).order_by('brand_name')
		
		return context

indie_app/templates/_global_partials/_global_menu.html
{% load url from future %}
{% load i18n %}

<!-- Global Menu (bottom ) -->
<section class="navigation">
    <header class="navigation__header">
        <a href="{% url "home" %}"><span class="navigation__header__branding">Unlabel</span></a>
        <a id="indie-global-menu-close" href="javascript:void(0)" class="navigation__header__close"><span class="icon-unlabel_web-01"></span></a>
    </header>
    <nav class="navigation__primary">
        {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
    </nav> 
    <nav class="navigation__icons">
        <ul>
            <li><a href="https://www.facebook.com/unlabel.us"><span class="icon-unlabel_web-02"></span></a></li>
            <li><a href="https://twitter.com/unlabel_us"><span class="icon-unlabel_web-04"></span></a></li>
            <li><a href="https://instagram.com/unlabel_us/"><span class="icon-unlabel_web-03"></span></a></li> 
        </ul>
    </nav>
    <p class="nav_copyright">&copy;2015 Unlabel. Built in NYC with love.</p>
</section>

indie_app/templates/_global_partials/_website_search.html
{% load url from future %}
{% load i18n %}
{% load cloudinary %}

<!-- Global Website search (top) -->
<section class="website-filtersearch overthrow">
    <header class="navigation__header navigation__header-search">
        <a id="indie-global-websearch-close" href="javascript:void(0)" class="navigation__header__close"><span class="icon-indie_web-03"></span></a>
    </header>   
    <div class="nav-sidebar" id="nav-filters">
        <div class="wrapper-nav">
            <h3 class="results">Filter Sites By:</h3>
            
            <div class="wrapper-dropdown" id="global-site-sex">
                <span>Categories</span>
                <ul id="website-sex" class="search-filter-container">
                   
                </ul>
            </div>

            <ul class="list-tags">
 
                <script id="listTagTemplate" type="text/template">

                  <% $.each(tags, function(filter_type, value) { %>
                    <li class="close style2"><a href="javascript:void(0)" data-filter-type="<%= filter_type %>"><%= value %></a></li>
                  <% }); %>
                </script>
            </ul>
        </div>
    </div> 
    <div id="indie-populate-websites" class="indie-fill-websites">
        <div class="indie-fill-panel-wrapper">
            <div id="sidebar_search_block" class="sidebar-block">      
                <script id="websiteTemplate" type="text/template">
                    <% $.each(websites, function(i, website) { %>
                        <% if(!website) { %>
                            <div class="empty">
                                <button class="btn btn-search-up btn-clear" type="button">
                                    <span class="text-hide">
                                        Go to Search.
                                    </span>
                                </button>
                                <p>No Websites Available! Filter Again Above.</p>
                            </div>
                    
                        <% } else { %>
                            <div class="og-expander">
                                <div class="og-expander-inner">
                                    <div class="og-fullimg">
                                        <img src="http://res.cloudinary.com/doqjl5owq/image/upload/<%= website.get('brand_logo') %>" style="display: inline;"></img>
                                    </div>
                                    <div class="og-details">
                                        <h3><%= website.get('brand_name') %></h3>
                                        <p><%= website.get('brand_description') %></p>
                                        <a href="<%= location.origin %>/brand/<%= website.get('slug') %>">Explore</a>
                                        <a href="javascript:void(0)">Mark <%= website.get('brand_name') %></a>
                                    </div>
                                </div>
                            </div>
                        <% } %>
                    <% }); %>
                </script>
            </div>
        </div>
        <!-- <div id="sidebar_right_loader" class="please-wait"><span class="text-hide">Loading...</span></div> -->
    </div>
</section>

indie_app/templates/_global_partials/ajax_login_brand_follow.html
{% load url from future %}
{% load i18n %}

<div id="content-form">
	<div class="block-form"></div>
	<div class="inner-form width-2">
    	<div class="box-login">
			<h1> Login </h1>
			<div class="ajax_wrapper_brand_follow">
			    <div class="socialconnect">
			        <a href="#" class="facebook">Login with your Facebook</a>
			        <a href="#" class="twitter">Sign-up with Twitter</a>
			    </div>
			     <p align="center"><strong>Or</strong></p>
			    <p align="center">Login with your Username & Password</p>
			    <form method="POST" action="{% url "account_login" %}" autocapitalize="off" {% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
			        {% csrf_token %}
			        {% if redirect_field_value %}
			            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
			        {% endif %}
			        
			        <div class="form-group">
			            <label class="control-label  " for="id_username">Username</label>
			            <div class="">
			                <input class=" form-control" id="id_username" maxlength="30" name="username" type="text" />   
			            </div>
			        </div>
			        
			        <div class="form-group">
			            <label class="control-label  " for="id_password">Password</label>
			            <div class=" ">
			                <input class=" form-control" id="id_password" name="password" type="password" />   
			            </div>   
			        </div>

			        <div class="form-group">
			            <div class="">
			                <div class="checkbox">
			                    <label><input id="id_remember" name="remember" type="checkbox" /> <span>Remember Me</span></label>
			                </div>
			            </div>   
			        </div>
			        <p><button type="submit" class="button large bold">{% trans "Login" %}</button></p>
			    </form>  
			    <div class="footer">
			        <h2 class="heading-title" align="center">Need to Signup? 
			            <a href="{% url "account_signup" %}">{% trans "Signup now" %}</a>
			        </h2>
			    </div>  
			</div>
		</div>
	</div>
</div>